import {
  MissionType,
  SkillType,
  AchievementType,
  ItemType,
  VillainType,
  ArtifactType,
} from "./Constants.js";

export const gameData = {
  score: 0,
  crystals: 0,
  totalScoreRun: 0,
  villainsDefeated: 0,
  totalClicks: 0,
  startTime: Date.now(),
  lastSaveTime: Date.now(),

  level: 1,
  clickDamage: 1,
  autoDamage: 0,

  villainMaxHp: 15,
  villainCurrentHp: 15,
  combo: 0,

  dailyMissions: {
    lastReset: Date.now(),
    completedToday: 0,
    currentMissions: [],
    rewardsClaimed: false,
    progress: {},
    stats: {
      skillsUsed: 0,
      clicksToday: 0,
      bossesDefeated: 0,
      maxComboToday: 0,
    },
  },

  achievements: {
    k10: {
      id: "k10",
      name: "Iniciante",
      desc: "Derrote 10 vilões",
      type: AchievementType.KILLS,
      req: 10,
      done: false,
      reward: 0.1,
    },
    c1000: {
      id: "c1000",
      name: "Dedo Rápido",
      desc: "Clique 1000 vezes",
      type: AchievementType.CLICKS,
      req: 1000,
      done: false,
      reward: 0.15,
    },
    l10: {
      id: "l10",
      name: "Patrulheiro",
      desc: "Alcance o Nível 10",
      type: AchievementType.LEVEL,
      req: 10,
      done: false,
      reward: 0.25,
    },
    k100: {
      id: "k100",
      name: "Vigilante",
      desc: "Derrote 100 vilões",
      type: AchievementType.KILLS,
      req: 100,
      done: false,
      reward: 0.2,
    },
    l25: {
      id: "l25",
      name: "Herói Local",
      desc: "Alcance o Nível 25",
      type: AchievementType.LEVEL,
      req: 25,
      done: false,
      reward: 0.5,
    },
  },

  upgrades: {
    gym: {
      name: "Academia",
      count: 0,
      baseCost: 15,
      boost: 1,
      icon: "fa-dumbbell",
      type: ItemType.UPGRADE,
    },
    brass: {
      name: "Soco Inglês",
      count: 0,
      baseCost: 150,
      boost: 5,
      icon: "fa-hand-rock",
      type: ItemType.UPGRADE,
    },
    gadget: {
      name: "Gadgets",
      count: 0,
      baseCost: 1100,
      boost: 20,
      icon: "fa-bullseye",
      type: ItemType.UPGRADE,
    },
    serum: {
      name: "Super Soro",
      count: 0,
      baseCost: 6500,
      boost: 75,
      icon: "fa-flask",
      type: ItemType.UPGRADE,
    },
    // === NOVAS SINERGIAS (FASE 2) ===
    team_training: {
      name: "Treino de Equipe",
      count: 0,
      baseCost: 2500,
      icon: "fa-users",
      type: ItemType.UPGRADE,
      synergy: true,
      targetTag: "human",
      mult: 1.5, // +50%
      desc: "Humanos +50% DPS",
    },
    tech_upgrade: {
      name: "Suporte Técnico",
      count: 0,
      baseCost: 15000,
      icon: "fa-microchip",
      type: ItemType.UPGRADE,
      synergy: true,
      targetTag: "tech",
      mult: 1.5,
      desc: "Tech +50% DPS",
    },
    suit: {
      name: "Traje Tecnológico",
      count: 0,
      baseCost: 45000,
      boost: 350,
      icon: "fa-user-astronaut",
      type: ItemType.UPGRADE,
    },
    metagene: {
      name: "Despertar Meta",
      count: 0,
      baseCost: 150000,
      icon: "fa-dna",
      type: ItemType.UPGRADE,
      synergy: true,
      targetTag: "meta",
      mult: 1.5,
      desc: "Metahumanos +50% DPS",
    },
    cosmic: {
      name: "Poder Cósmico",
      count: 0,
      baseCost: 350000,
      boost: 2000,
      icon: "fa-meteor",
      type: ItemType.UPGRADE,
    },
  },

  heroes: {
    kid: {
      name: "Ajudante Mirim",
      count: 0,
      baseCost: 50,
      dps: 2,
      icon: "fa-user-ninja",
      color: "text-yellow-500",
      type: ItemType.HERO,
      tags: ["human"],
    },
    vigilante: {
      name: "Vigilante Noturno",
      count: 0,
      baseCost: 450,
      dps: 12,
      icon: "fa-user-secret",
      color: "text-gray-800",
      type: ItemType.HERO,
      tags: ["human", "tech"], // Híbrido! Recebe bônus dos dois
    },
    speedster: {
      name: "Velocista",
      count: 0,
      baseCost: 2200,
      dps: 55,
      icon: "fa-bolt",
      color: "text-red-500",
      type: ItemType.HERO,
      tags: ["meta"],
    },
    amazon: {
      name: "Guerreira",
      count: 0,
      baseCost: 12000,
      dps: 250,
      icon: "fa-shield-alt",
      color: "text-yellow-600",
      type: ItemType.HERO,
      tags: ["meta", "divine"],
    },
    alien: {
      name: "Caçador Alien",
      count: 0,
      baseCost: 85000,
      dps: 1200,
      icon: "fa-rocket",
      color: "text-green-400",
      type: ItemType.HERO,
      tags: ["alien", "tech"],
    },
    wizard: {
      name: "Mago Supremo",
      count: 0,
      baseCost: 600000,
      dps: 7500,
      icon: "fa-hat-wizard",
      color: "text-purple-500",
      type: ItemType.HERO,
      tags: ["magic"],
    },
  },

  artifacts: {
    [ArtifactType.AMULET]: {
      name: "Amuleto Antigo",
      desc: "+10% Ouro dos Vilões",
      owned: false,
      icon: "fa-gem",
      color: "text-green-400",
    },
    [ArtifactType.RING]: {
      name: "Anel do Poder",
      desc: "+20% Dano de Clique",
      owned: false,
      icon: "fa-ring",
      color: "text-yellow-400",
    },
    [ArtifactType.CAPE]: {
      name: "Capa Heróica",
      desc: "+20% DPS Geral",
      owned: false,
      icon: "fa-mask",
      color: "text-gray-800",
    },
  },

  skills: {
    [SkillType.FURY]: {
      active: false,
      cooldown: 0,
      maxCooldown: 30000,
      duration: 5000,
    },
    [SkillType.CRIT]: {
      active: false,
      cooldown: 0,
      maxCooldown: 45000,
      duration: 10000,
    },
    [SkillType.TEAM]: {
      active: false,
      cooldown: 0,
      maxCooldown: 60000,
      duration: 10000,
    },
  },
};

export const villains = [
  { name: "Capanga", hp: 10, color: "text-gray-500", icon: "fa-user-ninja" },
  { name: "Palhaço", hp: 25, color: "text-red-500", icon: "fa-smile-wink" },
  { name: "Mutante", hp: 60, color: "text-green-600", icon: "fa-biohazard" },
  { name: "Ciborgue", hp: 150, color: "text-blue-500", icon: "fa-robot" },
  { name: "Sombra", hp: 400, color: "text-purple-600", icon: "fa-ghost" },
];

export const bosses = [
  {
    name: "Rei do Crime",
    hp: 2000,
    color: "text-yellow-600",
    icon: "fa-crown",
  },
  { name: "Titã Louco", hp: 50000, color: "text-purple-800", icon: "fa-gem" },
  { name: "Devorador", hp: 1000000, color: "text-red-900", icon: "fa-skull" },
];

export const specialVillains = [
  {
    name: "Tanque Blindado",
    type: VillainType.TANK,
    hpMod: 3.0,
    icon: "fa-mountain",
    effect: "Alta resistência",
    color: "text-gray-700",
  },
  {
    name: "Corredor Sombrio",
    type: VillainType.ELUSIVE,
    hpMod: 0.8,
    icon: "fa-running",
    effect: "Chance de Esquiva (30%)",
    color: "text-blue-400",
  },
  {
    name: "Regenerador",
    type: VillainType.HEALER,
    hpMod: 1.2,
    icon: "fa-heartbeat",
    effect: "Regenera vida",
    color: "text-green-500",
  },
];

export const dailyMissions = [
  {
    id: "kill_20",
    name: "Caçador de Recompensas",
    description: "Derrote 20 vilões",
    type: MissionType.KILL,
    target: 20,
    reward: { crystals: 2, gold: 500 },
    icon: "fa-skull",
  },
  {
    id: "use_skills_10",
    name: "Mestre das Habilidades",
    description: "Use habilidades 10 vezes",
    type: MissionType.SKILL_USE,
    target: 10,
    reward: { crystals: 3, gold: 300 },
    icon: "fa-fire",
  },
  {
    id: "reach_level_5",
    name: "Ascensão Heróica",
    description: "Alcance o nível 5",
    type: MissionType.LEVEL_UP,
    target: 5,
    reward: { crystals: 5, gold: 1000 },
    icon: "fa-arrow-up",
  },
  {
    id: "click_100",
    name: "Dedos Ligeiros",
    description: "Faça 100 cliques",
    type: MissionType.CLICK,
    target: 100,
    reward: { crystals: 1, gold: 200 },
    icon: "fa-hand-pointer",
  },
  {
    id: "defeat_boss",
    name: "Desafiador de Chefes",
    description: "Derrote 1 chefe",
    type: MissionType.BOSS_KILL,
    target: 1,
    reward: { crystals: 10, gold: 2000 },
    icon: "fa-crown",
  },
  {
    id: "combo_15",
    name: "Combo Master",
    description: "Alcance um combo de 15",
    type: MissionType.COMBO,
    target: 15,
    reward: { crystals: 4, gold: 800 },
    icon: "fa-bolt",
  },
];
