export const gameData = {
  score: 0,
  crystals: 0,
  totalScoreRun: 0,
  villainsDefeated: 0,
  totalClicks: 0,
  startTime: Date.now(),
  lastSaveTime: Date.now(),
  level: 1,
  clickDamage: 1,
  autoDamage: 0,
  villainMaxHp: 20,
  villainCurrentHp: 20,
  combo: 0,
  achievements: {
    kill10: {
      id: "kill10",
      name: "Vigilante Iniciante",
      desc: "Derrote 10 vilões",
      req: 10,
      type: "kills",
      reward: 0.1,
      done: false,
    },
    kill100: {
      id: "kill100",
      name: "Protetor da Cidade",
      desc: "Derrote 100 vilões",
      req: 100,
      type: "kills",
      reward: 0.2,
      done: false,
    },
    click500: {
      id: "click500",
      name: "Dedos Rápidos",
      desc: "500 Cliques",
      req: 500,
      type: "clicks",
      reward: 0.1,
      done: false,
    },
    level10: {
      id: "level10",
      name: "Subindo de Rank",
      desc: "Alcance Nível 10",
      req: 10,
      type: "level",
      reward: 0.2,
      done: false,
    },
  },
  upgrades: {
    gym: {
      id: "gym",
      name: "Academia de Boxe",
      baseCost: 15,
      count: 0,
      boost: 1,
      icon: "fa-dumbbell",
      type: "click",
    },
    brass: {
      id: "brass",
      name: "Soco Inglês",
      baseCost: 100,
      count: 0,
      boost: 5,
      icon: "fa-hand-rock",
      type: "click",
    },
    gadget: {
      id: "gadget",
      name: "Batarangue",
      baseCost: 500,
      count: 0,
      boost: 15,
      icon: "fa-bullseye",
      type: "click",
    },
    serum: {
      id: "serum",
      name: "Soro Experimental",
      baseCost: 2000,
      count: 0,
      boost: 50,
      icon: "fa-flask",
      type: "click",
    },
    suit: {
      id: "suit",
      name: "Traje de Nanotech",
      baseCost: 10000,
      count: 0,
      boost: 200,
      icon: "fa-user-astronaut",
      type: "click",
    },
  },
  heroes: {
    kid: {
      id: "kid",
      name: "Ajudante Mirim",
      baseCost: 50,
      count: 0,
      dps: 2,
      icon: "fa-user-ninja",
      color: "text-red-600",
    },
    vigilante: {
      id: "vigilante",
      name: "Vigilante Noturno",
      baseCost: 300,
      count: 0,
      dps: 10,
      icon: "fa-user-secret",
      color: "text-gray-800",
    },
    speedster: {
      id: "speedster",
      name: "Velocista",
      baseCost: 1500,
      count: 0,
      dps: 40,
      icon: "fa-bolt",
      color: "text-yellow-500",
    },
    amazon: {
      id: "amazon",
      name: "Guerreira Amazona",
      baseCost: 8000,
      count: 0,
      dps: 150,
      icon: "fa-shield-alt",
      color: "text-red-500",
    },
    alien: {
      id: "alien",
      name: "Último Filho",
      baseCost: 50000,
      count: 0,
      dps: 500,
      icon: "fa-rocket",
      color: "text-blue-600",
    },
  },
  artifacts: {
    amulet: {
      id: "amulet",
      name: "Amuleto da Sorte",
      desc: "+10% Ouro",
      owned: false,
      icon: "fa-gem",
      color: "text-green-400",
    },
    ring: {
      id: "ring",
      name: "Anel do Poder",
      desc: "+20% Dano Clique",
      owned: false,
      icon: "fa-ring",
      color: "text-yellow-400",
    },
    cape: {
      id: "cape",
      name: "Capa Sombria",
      desc: "+20% DPS",
      owned: false,
      icon: "fa-mask",
      color: "text-gray-800",
    },
  },
  skills: {
    fury: {
      active: false,
      cooldown: 0,
      maxCooldown: 30,
      duration: 5,
      effect: "dps_x2",
    },
    crit: {
      active: false,
      cooldown: 0,
      maxCooldown: 45,
      duration: 10,
      effect: "crit_chance",
    },
    team: {
      active: false,
      cooldown: 0,
      maxCooldown: 60,
      duration: 10,
      effect: "all_dmg_x2",
    },
  },
};

export const villains = [
  { name: "Punguista", icon: "fa-mask", color: "text-gray-500" },
  { name: "Capanga", icon: "fa-user-ninja", color: "text-blue-800" },
  { name: "Palhaço Louco", icon: "fa-smile", color: "text-red-600" },
  { name: "Mutante", icon: "fa-frog", color: "text-green-600" },
  { name: "Ciborgue", icon: "fa-robot", color: "text-gray-400" },
  { name: "Simbionte", icon: "fa-spider", color: "text-black" },
];

export const bosses = [
  "Rei do Crime",
  "Conquistador",
  "Titã Louco",
  "Devorador de Mundos",
];
